source 'https://rubygems.org'


gem 'rails', '4.2.1'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'

gem 'therubyracer'
gem 'devise'
gem 'omniauth'
gem 'omniauth-github'
gem 'dotenv-rails'


group :development, :test do
  gem 'pry-rails'
end

