source "https://rubygems.org"

gem "rails", "4.2.0"

gem "pg"
gem "sass-rails", "~> 5.0"
gem "uglifier", ">= 1.3.0"
gem "jquery-rails"
gem "kaminari"
gem "font-awesome-sass"

group :development, :test do
  gem "spring"
  gem "rspec-rails"
  gem "capybara"
  gem "factory_girl_rails"
end
